version: '3'
services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://${PRODUCTION_DB_USERNAME}:${PRODUCTION_DB_PASSWORD}@mysql:${PRODUCTION_DB_PORT}/${PRODUCTION_DB_NAME}
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:8.3.0
    environment:
      - PRODUCTION_DB_PASSWORD=${PRODUCTION_DB_PASSWORD}
      - PRODUCTION_DB_NAME=${PRODUCTION_DB_NAME}
    ports:
      - "3306:3306"
    env_file:
      - .env

