openapi: 3.0.0
info:
  title: Inforsion API Docs
  description: 사용자 회원가입 및 로그인을 위한 API
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: 개발 서버
paths:
  /auth/register:
    post:
      summary: 회원가입
      tags:
        - 인증
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  description: 사용자 이름
                email:
                  type: string
                  format: email
                  description: 사용자 이메일 주소
                password:
                  type: string
                  format: password
                  description: 사용자 비밀번호
      responses:
        '201':
          description: 사용자 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: '회원가입 성공'
        '400':
          description: 등록 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: '회원가입 실패'
  /auth/login:
    post:
      summary: 사용자 로그인
      tags:
        - 인증
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: 사용자 이메일 주소
                password:
                  type: string
                  format: password
                  description: 사용자 비밀번호
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: '로그인 성공!'
                  accessToken:
                    type: string
                    description: JWT 액세스 토큰
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        '400':
          description: 로그인 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: '로그인 실패'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer 토큰을 사용한 인증
security:
  - bearerAuth: []